galaxy_info:
  role_name: powershell
  author: Chris Bunge
  description: Installs PowerShell 7 on EL or Ubuntu Hosts
  company: Code the Things

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.9

  github_branch: master

  platforms:
    - name: EL
      versions:
      - 7
      - 8
    - name: Ubuntu
      versions:
      - focal
      - bionic
      - jammy

  galaxy_tags:
    - powershell

dependencies: []