galaxy_info:
  role_name: azure_cli
  author: Chris Bunge
  description: Installs Azure CLI and Additional CSP Packages on EL or Ubuntu Hosts
  company: Code the Things

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.9

  github_branch: master

  platforms:
    - name: EL
      versions:
      - 7
      - 8
      - 9
    - name: Ubuntu
      versions:
      - focal
      - bionic
      - jammy
      - noble

  galaxy_tags:
    - azure
    - azurecli
    - cloud
    - csp

dependencies:
  - powershell